### ISSUE TITLE
Chat

### ISSUE THREAD

**Issue by ErikPartridge** [ErikPartridge/AvGas#1]
Still need to do the migration, thinking some sort of string tag for what type of user or a specific user to send it to, or none if send to everyone. Timestamp, from, content probably enough.

**Comment by callahanp** [comment]
Chat Contacts: 

So we have a list of potential chat contacts drawn from user data from vatsim using some selection criteria

Chat Contact Attributes for selection - contact membership and privileges

Each potential chat contact could be a pilot, administrator, controller, project vector team, Boston Virtual ARTCC member, Vatsim member, Boston Virtual ATC Online team, etc.  

Chat Contact Attributes for selection - contact current status:

They could be online, online acting a pilot or controller,  online but inactive, offline, on vacation, away on business, working, last active as of date/time, do not disturb, unavailable etc.

Starting Chats:

Users might want to filter the list of potential chat contacts using one or more of the above criteria
Users might want to join an standard channel
Users might want to start an ad-hoc channel and select one or more of the potential chat contacts

Accepting and declining chat invites:

Invited potential chat contacts might want a chance to decline the chat, or they may want to automatically accept any chat invitation, any chat invitation to a specific channel, or any chat invitation from specific individuals.

Standard Chat Rooms:

There may be chats that we want to keep open and available all the time, similar to the way the teamspeak server channels work.   We may want to restrict access to some standard channels based on one or more of the criteria above.

**Comment by ErikPartridge** [comment]
Wow. Far more advanced than I was thinking. Gotta have this ready by August 14th at the latest btw.

I was thinking something like the chat here: http://vattastic.com/

Like where the default is a public chat room, but you could select a group in a small box to the left of the text box to shout to, or enter a csv list of VATSIM ids

If we want to make it all that advanced, I'm afraid I don't have the time to put in much more than basic features. I can do some user stuff and make the map work well, but I don't have time for much beyond a basic app with my other transition team obligations. If you want to, by all means, go ahead.

**Comment by callahanp** [comment]
Save the Wow for working code. Till then its just a vision.

August 14 gives us about two weeks to get it done.  
Does a very basic working meteor chat prototype by 8/3 sound realistic?
Give me a call and we can work out details of what to do first.

-Pat

 617 957-7239   Available between 6 pm and 10 pm 7/29
              between 6 am and 10 pm 7/30
              between 8 am and 10 pm 7/31
              between 6 am and 10 pm 8/1 & 8/2
        All times EDT.
