### ISSUE TITLE
CSS

### ISSUE THREAD

**Issue by ErikPartridge** [ErikPartridge/AvGas#2]
Planning Bootstap, but currently focused on it just looking okay.

**Comment by callahanp** [comment]
I'd go with Bootstrap, or even the customized control panel library used in the prototype, AdminLTE.
I think it would be best to do the integration up front so we don't end up with a big refactoring.

**Comment by callahanp** [comment]
suggestion: http://www.manuel-schoebel.com/blog/meteorjs-and-twitter-bootstrap---the-right-way

**Comment by ErikPartridge** [comment]
I'm fine with that. Personally I'm a sass guy but I can do less as well

**Comment by callahanp** [comment]
I'm agnostic about tools.  If SASS is integrated with bootstrap similarly to LESS, then we could easily adopt SASS as the standard.  I think Manuel's point is that we should avoid the pitfalls he pointed out in his  post.
